# Generated by Django 4.1.7 on 2023-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.FloatField(),
        ),
    ]
