# Generated by Django 4.1.7 on 2023-03-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsApp', '0002_part_amount_alter_part_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='price',
            new_name='price_netto',
        ),
    ]
